# Generated by Django 5.1.2 on 2024-12-08 13:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bursary', 'Bursary'), ('nsfas', 'NSFAS'), ('self_funded', 'Self-funded'), ('student_loan', 'Student Loan')], max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('uct', 'University of Cape Town'), ('uj', 'University of Johannesburg'), ('ukzn', 'University of Kwa-Zulu Natal'), ('wits', 'University of the Witwatersrand'), ('ufs', 'University of the Free State'), ('up', 'University of Pretoria'), ('uwc', 'University of the Western Cape'), ('ul', 'University of Limpopo'), ('nwu', 'Northwest University'), ('univen', 'University of Venda'), ('other', 'Other')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('distance_to_campus', models.DecimalField(decimal_places=2, help_text='Distance to campus in kilometers', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_size', models.DecimalField(decimal_places=2, help_text='Size in square meters', max_digits=6)),
                ('max_occupants', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('furnished', models.BooleanField(default=False)),
                ('gender_restriction', models.CharField(choices=[('any', 'Any Gender'), ('female', 'Female Only'), ('male', 'Male Only')], default='any', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('available_from', models.DateField()),
                ('minimum_lease_period', models.PositiveIntegerField(default=12, help_text='Minimum lease period in months')),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL)),
                ('amenities', models.ManyToManyField(related_name='accommodations', to='accomodations.amenity')),
                ('accepted_payments', models.ManyToManyField(related_name='accommodations', to='accomodations.paymentmethod')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accomodations.propertytype')),
                ('universities', models.ManyToManyField(related_name='accommodations', to='accomodations.university')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['city', 'province'], name='accomodatio_city_2616aa_idx'), models.Index(fields=['is_available', 'available_from'], name='accomodatio_is_avai_941e5b_idx'), models.Index(fields=['monthly_rent'], name='accomodatio_monthly_ca1879_idx')],
            },
        ),
    ]
